# Generated by Django 5.2.4 on 2025-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tana qismi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Chiqim nomi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('note', models.TextField(blank=True, verbose_name='Eslatma')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('birth_year', models.IntegerField(verbose_name="Tug'ilgan yil")),
                ('notes', models.TextField(blank=True, verbose_name='Eslatmalar')),
                ('appointment_number', models.CharField(max_length=10, unique=True, verbose_name='Navbat raqami')),
                ('registered', models.BooleanField(default=False, verbose_name="Ro'yxatdan o'tgan")),
                ('paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('partial_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Qisman to'lov")),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tkazilgan sana")),
                ('missed', models.BooleanField(default=False, verbose_name="Navbatini o'tkazib yuborgan")),
                ('body_parts', models.ManyToManyField(to='apps.bodypart', verbose_name='Skani qilinadigan joylar')),
            ],
        ),
    ]
