# Generated by Django 5.2.4 on 2025-07-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointment_number',
            field=models.CharField(max_length=10, verbose_name='Navbat raqami'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('appointment_number', 'registration_date'), name='unique_appointment_per_day'),
        ),
    ]
