# Generated by Django 5.2.4 on 2025-07-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_patient_appointment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Tugallangan (TVda ko‘rinmasin)'),
        ),
    ]
