# Generated by Django 5.2.4 on 2025-07-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_patient_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
    ]
